services:
- mfe-a: "*"
- service-b: "*" 

dependencies:
- shared-app/service-s: "~0.0.1"

links:
- source: mfe-a
  target: service-b
- source: service-b
  target: shared-app/service-s

# semver guide
# * means always take the latest no matter what
# ~ means always take the latest patch or minor version
# ^ means always take the latest patch