name: Sleep and Maybe Fail

on:
  workflow_dispatch:

jobs:
  sleep-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Sleep for 10 seconds
        run: sleep 10
        
      - name: Randomly fail with 30% chance
        run: |
          # Generate a random number between 1-10
          RANDOM_NUM=$(( $RANDOM % 10 + 1 ))
          
          # If number is <= 3 (30% chance), exit with failure
          if [ $RANDOM_NUM -le 3 ]; then
            echo "Bad luck! 30% chance of failure triggered (rolled a $RANDOM_NUM)."
            exit 1
          else
            echo "Success! Avoided failure (rolled a $RANDOM_NUM)."
          fi